#!/bin/bash

OS="$(uname)"

# TODO: make sure this works
# ctags for osx and linux
case $"OS" in
	'Linux') CTAG_OPTIONS="ctags -R --exclude=.git" ;;
	'Darwin') CTAG_OPTIONS="`brew --prefix` /bin/ctags -R --exclude=.git" ;;
esac
alias ctags=$CTAG_OPTIONS

# print in human readable form
alias df="df -h"

# start dlv debug headless on api version 2
alias dlv-debug="dlv debug --headless --listen=:2345 --api-version 2 --log"

# print in human readable form
alias df="df -h"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias mus="cd ~/Music"
alias pic="cd ~/Pictures"
alias src="cd ~/Source"
alias vid="cd ~/Videos"
alias g="git"
alias h="history"

# untar
alias untar='tar xvf'

# Stopwatch
alias timer=echo "Timer started. Stop with Ctrl-D." && date && time cat && date

# Pipe my public key to my clipboard.
alias pubkey="more ~/.ssh/id_rsa.pub | xclip -selection clipboard | echo '=> Public key copied to pasteboard.'"

# Pipe my private key to my clipboard.
alias prikey="more ~/.ssh/id_rsa | xclip -selection clipboard | echo '=> Private key copied to pasteboard.'"

alias set-token="jq '.token' | tr -d '\"' | { read TOKEN }"

