#!/bin/bash

OS="$(uname)"

# TODO: make sure this works
# ctags for osx and linux
case $"OS" in
	'Linux') CTAG_OPTIONS="ctags -R --exclude=.git" ;;
	'Darwin') CTAG_OPTIONS="`brew --prefix` /bin/ctags -R --exclude=.git" ;;
esac
alias ctags=$CTAG_OPTIONS

# print in human readable form
alias df="df -h"

# start dlv debug headless on api version 2
alias dlv-debug="dlv debug --headless --listen=:2345 --api-version 2 --log"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias dl="cd ~/Downloads"
alias doc="cd ~/Documents"
alias key="cd ~/Documents/keys"
alias mus="cd ~/Music"
alias pic="cd ~/Pictures"
alias src="cd ~/Source"
alias vid="cd ~/Videos"
alias gs="cd ~/Source/go"
alias nsrc="cd ~/Source/go/src/bitbucket.org/noke"

alias gsnd="cd ~/Source/go/src/github.com/n7down"
alias g="git"
alias h="history"
alias dots="~/Source/dotfiles"

alias gpo="git push origin"
alias guo="git pull origin"
alias gpot="git push origin --tags"

# untar
alias untar='tar xvf'

# Stopwatch
alias timer=echo "Timer started. Stop with Ctrl-D." && date && time cat && date

# Pipe my public key to my clipboard.
alias pubkey="more ~/.ssh/id_rsa.pub | xclip -selection clipboard | echo '=> Public key copied to pasteboard.'"

# Pipe my private key to my clipboard.
alias prikey="more ~/.ssh/id_rsa | xclip -selection clipboard | echo '=> Private key copied to pasteboard.'"

alias pri='export SSH_PRIVATE_KEY=\"`sed -E 's/$/\\\n/g' ~/.ssh/id_rsa`\"'

alias set-token="jq '.token' | sed -e 's/^\"//' -e 's/\"$//' | { read TOKEN }"

# restarting go servers on save
alias gre="ag -l | entr -r go run"

# copy to system clipboard for linux
alias cclip="xclip -selection clipboard"

# docker
alias dcp='docker-compose'
alias dk='docker'
alias dki='docker images'
alias dks='docker service'
alias dkrm='docker rm'
alias dkrmf='docker rm -f'
alias dkpsa='docker ps -a'
alias dkl='docker logs'
alias dklf='docker logs -f'
alias dkrmi='docker rmi $(docker images -qa)'
alias dkflush='docker rm `docker ps --no-trunc -aq`'
alias dkflush2='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias dkt='docker stats --format "table {{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}"'
alias dkps='docker ps --format "{{.ID}} ~ {{.Names}} ~ {{.Status}} ~ {{.Image}}"'
alias dkex='docker exec'
alias dkal='docker images && docker ps -a'

