#!/bin/bash

# Deletes all images and containers
# TODO: figure this out - https://www.shellhacks.com/yes-no-bash-script-prompt-confirmation/
dda() {
	# TODO: get this to work
	echo -n "Confirm to delete all docker images and containers y/[n]: "
	read -n 1 response
	if [ "$response" = "y" ]; then
		#docker rm -f $(docker ps -aq) && docker rmi $(docker images -aq)
		echo "Deleting docker images and containers"
	fi
}

# Deletes all images
ddi() {

}

# Delete all containers
ddc() {

}

ddt() {
	read -p "Do you wish to install this program?" yn
	case $yn in
		[Yy]* ) make install; break;;
		[Nn]* ) exit;;
		* ) echo "Please answer yes or no.";;
	esac
}
