#!/usr/bin/env bash

# TODO:
# press print screen
# ask screenshot? yes no
# if yes take screenshot of the full screen

# Script name: dmscrot
# Description: Choose type of screenshot to take with maim.
# Dependencies: dmenu, maim, tee, xdotool, xclip
# GitLab: https://www.gitlab.com/dwt1/dmscripts
# License: https://www.gitlab.com/dwt1/dmscripts/LICENSE
# Contributors: Derek Taylor
#               Simon Ingelsson
#               Steven Hall

# Set with the flags "-e", "-u","-o pipefail" cause the script to fail
# if certain things happen, which is a good thing.  Otherwise, we can
# get hidden bugs that are hard to discover.
set -euo pipefail

# Specifying a directory to save our screenshots.
SCROTDIR="$HOME/Pictures"

# Makes sure the directory exists.
mkdir -p "${SCROTDIR}"

getStamp() {
  date '+%Y%m%d-%H%M%S'
}

MAIM_ARGS=""
FILE_TYPE=""

# Get monitors and their settings for maim
DISPLAYS=$(xrandr --listactivemonitors | grep '+' | awk '{print $4, $3}' | awk -F'[x/+* ]' '{print $1,$2"x"$4"+"$6"+"$7}')

# What modes do we have
declare -a modes=(
"fullscreen"
"active window"
"selected region"
)

# Add monitor data
IFS=$'\n'
declare -A DISPLAY_MODE
for i in ${DISPLAYS}; do
  name=$(echo "${i}" | awk '{print $1}')
  rest="$(echo "${i}" | awk '{print $2}')"
  modes[${#modes[@]}]="${name}"
  DISPLAY_MODE[${name}]="${rest}"
done
unset IFS

target=$(printf '%s\n' "${modes[@]}" | dmenu -i -l 20 -fn 'Source Code Pro:style=regular:size=8' -p 'take screenshot of') || exit 1
case "$target" in
  'fullscreen')
    FILE_TYPE="full"
  ;;
  'active window')
    active_window=$(xdotool getactivewindow)
    MAIM_ARGS="-i ${active_window}"
    FILE_TYPE="window"
  ;;
  'selected region')
    MAIM_ARGS="-s"
    FILE_TYPE="region"
  ;;
  *)
    MAIM_ARGS="-g ${DISPLAY_MODE[${target}]}"
    FILE_TYPE="${target}"
  ;;
esac

declare -a destination=( "file" "clipboard" "both" )
dest=$(printf '%s\n' "${destination[@]}" | dmenu -i -l 20 -fn 'Source Code pro:style=regular:size=8' -p 'destination') || exit 1
case "$dest" in
  'file')
    # shellcheck disable=SC2086
    maim ${MAIM_ARGS} "${SCROTDIR}/scrot-${FILE_TYPE}-$(getStamp).png"
  ;;
  'clipboard')
    # shellcheck disable=SC2086
    maim ${MAIM_ARGS} | xclip -selection clipboard -t image/png
  ;;
  'both')
    # shellcheck disable=SC2086
    maim ${MAIM_ARGS} | tee "${SCROTDIR}/scrot-${FILE_TYPE}-$(getStamp).png" | xclip -selection clipboard -t image/png
  ;;
  *)
    exit 1
  ;;
esac

exit 0

