#!/usr/bin/expect -f
set name [lrange $argv 0 0]
set pass [lrange $argv 1 1]
set server [lrange $argv 2 2]
set key [lrange $argv 3 3]

spawn ssh -i $key $name@$server
match_max 100000
expect "*?nter*"
send -- "$pass\r"
send -- "\r"
interact
