#!/bin/bash

if synclient -l | grep "TouchpadOff .*=.*0" ; then 
	# TODO: add dunst notification
	#dunstify 'Touchpad' 'Off' && synclient TouchpadOff=1
	synclient TouchpadOff=1
else
	#dunstify 'Touchpad' 'On' && synclient TouchpadOff=0
	synclient TouchpadOff=0
fi
