#!/bin/sh

# wacom setup
# 1. Setup monitors with arandr - put DP2-1 under eDP1 and inverse DP2-1
# - May have to use monitor - ${env:MONITOR:} in polybar config
# - Update launch-polybar.sh to work with wacom instead of econdary monitor
# 2. polybar --reload main-bar & with eDP1
# 3. polybar --reload wacom-bar & with DP2-1
# 4. xsetwacom list to get STYLUS_ID
# 5. xsetwacom set <STYLUS_ID> MapToOutput DP2-1
# 6. xsetwacom set <STYLUS_ID> Rotate half
# 7. [Setup wacom buttons](https://wiki.archlinux.org/index.php/Wacom_tablet)

case "$1" in 
    "start")
        ~/.screenlayout/wacom.sh
        killall polybar
        sleep 1
        bspc wm -r
        sleep 1
        pkill -f "polybar main-bar"
        polybar main-multiple-monitors-bar &
        polybar wacom-bar &
        xsetwacom set "Wacom Cintiq 13HD Pen stylus" MapToOutput DP2-1
        xsetwacom set "Wacom Cintiq 13HD Pen stylus" Rotate half
        ;;
    "stop")
        ~/.screenlayout/laptop.sh
        # pkill -f "polybar wacom-bar"
        killall polybar
        sleep 1
        bspc wm -r
        ;;
    "reset")
        xsetwacom set "Wacom Cintiq 13HD Pen stylus" MapToOutput DP2-1
        xsetwacom set "Wacom Cintiq 13HD Pen stylus" Rotate half
        ;;
    *)
        echo "Wacom is a tool of setting up a wacom table"
        echo ""
        echo "Usage:"
        echo ""
        echo "  start       starts the wacom as a new screen and configures the stylus"
        echo "  stop        stop the wacom as a screen"
        echo "  reset       resets the stylus"
        ;;
esac


