#! /bin/sh

bspc monitor eDP1 -n 1 -d 1 2 3 4 5 6 7 8
bspc monitor DP2-1 -n 2 -d 9 10

bspc config border_width         2
bspc config window_gap           7

# border colors
bspc config normal_border_color "#484848"
bspc config focused_border_color "#1F8999"
# bspc config urgent_border_color "#B58900"
# bspc config presel_border_color "#26E2FF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# start sxhkd
sxhkd &

# start polybar
polybar main-bar &

# start mpd
mpd &

feh --bg-scale $HOME/Pictures/wallpapers/wallpaper.png
